### ISSUE TITLE
Vitesse des gifs - Dispositif H5P

### ISSUE THREAD

**Issue by BBberghman** [parastuffs/esnu#5]
Les gifs vidéos présentant les dispositifs H5P sont trop rapides, c'est difficile de suivre ce qu'il se passe. De plus, le fait que ça tourne en boucle et qu'on ne peut pas les commencer quand on le souhaite rend la navigation moins agréable.

Voir : https://parastuffs.github.io/esnu/tester-maitrise-logiciel

**Comment by parastuffs** [comment]
Fixed in 749db136dfc4214db141a365b9f07816262883ad
